### ISSUE TITLE
FY21 Deliverables Discussion

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#101]
# ISSUE/DISCUSSION IN PROGRESS

## Migration of Existing Data Products from CPC

Details: https://github.com/USACE/cumulus/blob/develop/CPC-MIGRATION.md

## New Data Product Additions

- [ ] Soil Moisture (Need Specific Products)
- [ ] Long Range Forecasts (Need Specific Products)
- [ ] MBRFC Data Products (Need Specific Products)
- [ ] MRMS Version 1 Archive from Iowa State Website (See USACE/cumulus#51)
  - [ ] 1 Hour Gauge Corrected Precipitation (November 2014 - ?)
  - [ ] 1 Hour Radar Only Precipitation (November 2014 - ?)
- [ ] National Blended Model (NBM) (Need Specific Products) (USACE/cumulus#105)
- [ ] Alaska RFC (USACE/cumulus#70)

## Documentation

- [ ] Diagram of Cumulus Architecture and Components
    - [ ] Airflow
    - [ ] elasticmq (SQS)
    - [ ] minio (S3)
    - [ ] API
    - [ ] geoprocess
    - [ ] listener
    - [ ] packager
    - [ ] etc
- [ ] Simple Documentation
- [ ] Cloud Configuration / Infrastructure

## User Interface

- [ ] Catalog
    - [ ] Decade rollup of heatmap
    - [ ] Log of missing productfiles by day
- [ ] Admin Functionality
- [ ] Product Descriptions
- [ ] Data Explorer (Mapping Capability)

## Training

- [ ] 30-minute demonstration webinars (3x)
- [ ]
