### ISSUE TITLE
[CHECKLIST]: FY22 New Products

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#129]
## General Description
Another new products list based on latest requests.  Should reconcile against existing list in another github issue checklist.

## FY22 list
- [ ] SNODAS:  2004-2010 raw grids and compute interpolated version
- [ ] Soil Moisture - NLDAS and SMAP
- [ ] OHRFC (POCs:  Charles Kottler-LRD and James (Brandon) Kolze-LRL)
- [ ] APRFC (POCs:  Kevin McAllister and Lewis (Nathan) Epps)
- [ ] NWRFC (POCs: Art Armour)
- [ ] LMRFC (POCs: Timothy Belles/Holly Enlow-MVM and 
- [ ] MARFC (POCs: Tom Ressin)
       MARFC_xmrgMMDDYYYYHHz - hourly observed precip
       MARFC_xmrg6_YYYYMMDDHHf0XX - 6 hour qpf XX hours (06 to 72) from present
       RHA_T_RTMA_1hr.YYYY-MM-DD.HHz.grb - hourly observed air temp
       RHA_T_NBM_XXhr.YYYY-MM-DD.HHz.grb - 1/3 hour forecast air temp XX hours (1-99) from present
       FMATXXhr_YYYYMMDD.HHz.grb - 6 hour forecast air temp XX hours (6-96) from present
- [ ] NERFC (POCs: Stephen Kissock
       REQUEST   ANY   (nerfc2coe.qpe)(.*)(.grb)             198.206.45.200
      REQUEST   ANY   "nerfc.qpf"                           198.206.45.200
- [ ] WGRFC (POCs:  Michael Schwind and James Moffitt)
- [ ] ABRFC (POCs: Lisa Samilton-SWT)
- [ ] CBRFC (POCs: Roberta Ball-SPA and Jason Lee-SPL)
- [ ] NCRFC (POCs: Brett Novotny-MVP)
- [ ] CNRFC (POCs: )
- [ ] MBRFC (POCs: Alex Flaningan-NWO and Brian Twombly/Paul Simon NWK)
- [ ] SERFC (POCs: Scott C.-SAM and Stan Simpson-SAS)
- [ ] National Water Model

**Comment by brettpalmberg** [comment]
Let's also revisit naming conventions

**Comment by brettpalmberg** [comment]
Products in the FY22 list above have been moved to separate github issues. Relevant GH Issue numbers have been added to the list for reference. The best way to track progress on new products added to Cumulus is to use Github filters. All Product-Related Issues are now prefixed in their title with `[PRODUCT]:`

**Comment by adamscarberry** [comment]
@brettpalmberg Can we close this laundry list issue since you broke the out into separate issues a while back?
