### ISSUE TITLE
[CHECKLIST]: Migrate to New AWS Account (develop)

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#149]
## General Description

Migrate `development` data and database records to new AWS "Castle" account

## Migration
- [x] Stop Data Acquisition to current `develop` instance
- [x] Database pgdump
- [x] Sync `develop` S3 Bucket data to bucket in new environment
- [x] Truncate all tables, except for `flyway_schema_history`, `config` 
- [x] Disable Triggers
    - [x] acquirablefile
    - [x] productfile
    - [x] download
- [x] Import pgdump data into new database
- [x] Enable Triggers
    - [x] acquirablefile
    - [x] productfile
    - [x] download
- [x] Turn on new cumulus services & validate operation
- [x] Start Airflow `develop` workflows & validate results
- [x] Allow role for LDM to write to bucket
- [x] Allow LDM IP address access to Cumulus REST API via security group
- [x] Validate results
- [x] Retrospective

**Comment by brettpalmberg** [comment]
# Retrospective Notes

## Good
- Effective teamwork, ownership in strength areas
- Containerized S3 and database backup utilities worked well
- Infrastructure as code (Terraform) worked well to replicate `develop` to `stable`

## Lessons Learned
- RDS limited permissions on disabling triggers, even as rds_superuser.  A pg_restore with the --disable-triggers flag will attempt to run commands that the rds_superuser is not able to run on import, resulting on failed imports. The export/import process was extensively tested locally; however, this would not have been identified until testing against an RDS database.
- Set all airflow lookback times for realtime data to a relative time (2 weeks ago, 2 days ago, 1 hour ago, etc.)
- `cumulus-api` async_geoprocess container needs additional try/except logic. Right now, there is limited error handling and small errors can cause a crash and restart of the container.

**Comment by brettpalmberg** [comment]
Validation of results and LDM data transmission development are ongoing. These will be tracked under USACE/cumulus#153. Closing this issue.
