### ISSUE TITLE
[CHECKLIST]: Migrate Auth to Keycloak Service

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#150]
## API
- [x] Remove tables & views that use `profile` and `role` tables
- [x] Update SQL for API Endpoints
- [x] Implement Middleware to handle updated auth server & token format
- [x] Update Regression Tests
- [x] Update API Docs

## UI
- [ ] Add Information Here

**Comment by brettpalmberg** [comment]
UI Changes will be addressed in separate issues as needed. Closing now.
