### ISSUE TITLE
[CHECKLIST]: Migration to corps.cloud Domain

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#153]
## General Description

This captures all tasks related to migrating the `develop` and `stable` instances of Cumulus from one account to another, and from hosting at *.rsgis.dev to *.corps.cloud.

### LDM

- [x] Create Role LDM in Castle Cloud
  - [x] Write to Bucket
  - [x] Access to Cumulus REST API
    - [x] Allow Network Traffic
    - [x] New API Key
  - [x] Set new credentials in LDM environment
  - [x] Restart LDM Container
  - [x] Turn on LDM data acquisition and posting to `castle develop` environment
    - [x] Confirm working

### Airflow
- [x] Branch Reconfiguring at https://github.com/USACE/airflow-config
  - [x] Rename Branch: develop --> rsgis_dot_dev
    - [x] Terraform Develop Environment: Set Airflow Sync Branch to rsgis_dot_dev
  - [x] Rename Branch: castle_develop --> develop
  - [x] Rename Branch: castle_stable --> stable
  - [x] Terraform Castle Environment: Set Airflow Sync Branch to `develop`

### Data Migration

- [x] Migrate S3 Data
- [x] Update postgres-s3-import-export :https://github.com/USACE/cumulus/issues/159
- [x] #161
  - [x] tables: `acquirablefile` `download` `download_product` `productfile` `area` `area_group` `area_group_product_statistics` `product_tags`  `product`
  - Issue: `product_tags` have seed data, should be deleted so import can assign correctly. Resolution: **Restore CWBI Stable data**. 
  - Issue: `product` labels/descriptions in CWBI stable may not match seed data.  Result of fixing names/labels in the admin UI.  Resolution: **Restore CWBI Stable data**. 
- [x] Database Import

### Airflow DAGs
- [x] #156

### Cumulus API
- [x] Reconfigure Github Branches
  - [x] Rename Branch `stable` --> `rsgis_dot_dev`
  - [x] Rework Github Workflows for `stable`
- [x] Deploy With New Authentication Middleware

### Offline Access Tokens Capability
- [x] #157
- [ ] Test Implementation in `develop`

**Comment by brettpalmberg** [comment]
Branch refactoring and associated infrastructure changes for repository USACE/airflow-config complete.  @adamscarberry @jeffsuperglide

**Comment by brettpalmberg** [comment]
> Rework Github Workflows for stable

✅ Merged; https://github.com/USACE/cumulus-api/pull/179

**Comment by brettpalmberg** [comment]
LDM User w/ capability to write to required S3 Buckets generated and incorporated in Infrastructure as Code.  Access Key ID, Secret Access Key provided to @jeffsuperglide .

**Comment by brettpalmberg** [comment]
> - [x] Migrate S3 Data

Data migration from `dev account` bucket to `castle account` bucket is now caught-up.  Files are still being written to `dev account` bucket; however, delta between buckets should now be small when it comes time to run final bucket sync and switch-over the service.

S3 sync container exited at `2022-01-25 17:15:07 -0600` for reason `Essential container in task exited` 👍🏻  Log entry confirms s3 sync complete:
![image](https://user-images.githubusercontent.com/29417036/151077341-ce1397c7-1964-4135-b4da-4dfa373f6b25.png)

**Comment by brettpalmberg** [comment]
Substantially complete.  Will target a retrospective for next week. Good work all!

**Comment by brettpalmberg** [comment]
LDM Migration complete and confirmed working.

Offline token capability to support scripted downloads will be tracked via a separate issue (to be created). Capability for users to create offline tokens in the cumulus-ui to be implemented here: https://github.com/USACE/usace-bundles/issues/1
