### ISSUE TITLE
[CHECKLIST]: Develop previous `Dev Environment ` Deprecation Plan

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#163]
## General Description
A clear and concise description

## Prerequisites
- [x] Tokn Deployment to Beta Testers
  **_Forego Tokn Deployment at this time_**
- [x] Temporarily support anonymous downloads via API (USACE/cumulus-api#293)
- [x] Update CAVI Scripts to use new endpoint `/deprecated/anonymous_downloads`
- [x] Castle Airflow Stable running in "stable" condition
- [x] rts-utils documentation on headless mode vs. GUI mode @jeffsuperglide

## How to Spin-Down Environment
- [x] Notify users of new rts-utils. Begin migrating users to new service @FHanbali 
- [ ] ~~Simple page "Cumulus Has Moved" (Redirect to new URL in 10s)~~
- [x] #282
- [x] #320
- [x] Delete S3 Data (Already available in Castle Environment)

**Comment by willbreitkreutz** [comment]
Once we are confident in the corps.cloud instance of the tools then we can shut down cumulus resources in the Dev cloud account, we will need to identify and list each of the services/deployments here and make sure they are all turned off or deleted.

**Comment by brettpalmberg** [comment]
Going to support Anon Downloads in new environment as a stop-gap. Will need to patch-in fake AnonUser information via API Middleware so SQL constraints are satisfied.

**Comment by brettpalmberg** [comment]
> Will need to patch-in fake AnonUser information via API Middleware so SQL constraints are satisfied.

This was added via PR USACE/cumulus-api#293. @jeffsuperglide, there is an endpoint `POST /deprecated/anonymous_downloads` live in the develop-cumulus-api in Castle. Can you lead the necessary changes to to the CAVI Scripts? If the endpoint appears to work well in `develop`, we can deploy to `stable`.

**Comment by jeffsuperglide** [comment]
@brettpalmberg - rts-utils updated on `develop` and `stable`.  Works in cumulus `develop`.

**Comment by brettpalmberg** [comment]
> @brettpalmberg - rts-utils updated on `develop` and `stable`. Works in cumulus `develop`.

Awesome!  Thanks @jeffsuperglide . When convenient, @adamscarberry , can you put the new version through a few paces?

**Comment by adamscarberry** [comment]
setup of script and test run was successful on PC (w/VPN enabled). Only minor complaint would be the lack of status to user while scripts are running.  Leaves user with a feeling of "is this working...should I wait longer".  Otherwise it should be fine.

**Comment by brettpalmberg** [comment]
>  Castle Airflow Stable running in "stable" condition

* In progress. Updating Airflow to 2.3.2, clean database initialization.

**Comment by brettpalmberg** [comment]
@jeffsuperglide, can you add some information on GUI Mode vs. Headless mode in the wiki?  cc @adamscarberry may have some ideas too

**Comment by brettpalmberg** [comment]
> > Castle Airflow Stable running in "stable" condition
> 
> * In progress. Updating Airflow to 2.3.2, clean database initialization.

✅ Done.  Running and appears stable. Marking this task as complete.

**Comment by jeffsuperglide** [comment]
@brettpalmberg @adamscarberry - Updated `rts-utils` wiki.  Added some update/install and cumulus headless mode.

**Comment by adamscarberry** [comment]
rts-utils wiki updates look good @jeffsuperglide

**Comment by brettpalmberg** [comment]
Good stuff guys. Thanks @jeffsuperglide.

**Comment by brettpalmberg** [comment]
> Notify users of new rts-utils. Begin migrating users to new service @FHanbali

Have begun migrating users to new service at `cumulus.corps.cloud`. Plan to spin-down legacy `dev` cloud resources in 2 weeks after providing time for users to migrate.

cc @FHanbali @LSEETHALER @willbreitkreutz @adamscarberry @jeffsuperglide

**Comment by brettpalmberg** [comment]
> Have begun migrating users to new service at cumulus.corps.cloud. Plan to spin-down legacy dev cloud resources in 2 weeks after providing time for users to migrate.

Has been requested that we delay turning off existing services by 1 week. New target date to spin-down rsgis.dev cumulus services is Monday, August 15th, 2022.

**Comment by brettpalmberg** [comment]
Outward-facing load balancer listener rules for api and user interface removed earlier today.
