### ISSUE TITLE
[CHECKLIST]: Misc. Repository Refactor

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#175]
## General Description

Misc Repository Refactor

## List Title
- [ ] Update Go runtime to 1.17.
- [ ] Minimize use of bind mounts in local development
- [ ] Build dedicated cumulus-sql container for migrating database
  - [ ] Associated infrastructure as code changes
