### ISSUE TITLE
[CHECKLIST]: Inventory CPC Archives Imported into Cumulus

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#194]
## General Description
Clear list of products on CPC Grid Server that have been (or need to be) saved and/or imported into Cumulus

**_Recommend we don't load forecast archives into Cumulus_**

## CBRFC MPE
- [x] 2019 (Jan - Dec)
- [x] 2020 (Jan - Dec)
- [x] 2021 (Jan - Apr)

:white_check_mark: Done via https://github.com/USACE/cumulus/issues/211

Note: none of the archives from CPC had a full 24 hours

## HRRR-forecast_precip

Each month has ~11,848 files and ~1.3TB in size.

Files have been deleted (May 2022) to recover space on CPC server.  No HRRR grids will be migrated/imported.

:white_check_mark:

## NCEP-MRMS_GaugeCorr_QPE_01H
- [ ] 2019 (Jan - Dec)
- [ ] 2020 (Jan - Dec)
- [ ] 2021 (Jan - Dec)
- [ ] 2022 (Jan - Mar)

## NCEP-rtma_airtemp (NDGD RTMA AIRTEMP 1hr)
- 2018 (Jan - Oct) - already in Cumulus
- [ ] 2018 (Nov - Dec) - gaps in Cumulus
- [x] 2019 (Jan - Dec) - gaps in Cumulus https://github.com/USACE/cumulus/issues/223
- [x] 2020 (Jan - Dec) - gaps in Cumulus https://github.com/USACE/cumulus/issues/223
- [x] 2021 (Apr - Jun) - gaps in Cumulus https://github.com/USACE/cumulus/issues/223
- 2022 (Jan - Mar) - already in Cumulus

## NCEP-rtma_precip (NDGD RTMA PRECIP 1hr)
- [ ] 2011 - 2017 leia98_raw
- [ ] 2018 (Jan - Dec)
- [ ] 2019 (Jan - Dec) 2019-10 - 2019-12 loaded here: https://github.com/USACE/cumulus/issues/191
- [x] 2020 (Jan - Dec) 2020-01 - 2020-12 loaded here: https://github.com/USACE/cumulus/issues/191
- [ ] 2021 (Jan - Dec) 2021-01 - 2021-06 loaded here: https://github.com/USACE/cumulus/issues/191
- 2022 (Jan - Mar) - already in Cumulus

## NDFD-forecast_airtemp_vp_001_003
- [ ] 2018 (Jan - Dec)
- [ ] 2019 (Jan - Dec)
- [ ] 2020 (Jan - Dec)
- [ ] 2021 (Jan - May) Jun - Dec already in Cumulus
- 2022 (Jan - Mar) already in Cumulus

## NDFD-forecast_airtemp_vp_004_007 (NDFD AIRTEMP 6hr)
- [ ] 2018 (Jan - Oct)

## NDFD-forecast_precip_vp_001_003
- [ ] 2018 (Jan - Dec)
- [ ] 2019 (Jan - Dec)
- [ ] 2020 (Jan - Dec)
- [ ] 2021 (Jan - Dec)
- [ ] 2022 (Jan - Mar)

This product is not in Cumulus

## NOHRSC-snodas

Cumulus has the full archive back to 2010

## NOHRSC-snodas_interpolated

Cumulus has the full archive back to 2010

## WPC-qpf_2p5km

- [ ] 2018 (Aug - Dec)
- [ ] 2019 (Jan - Dec)
- [ ] 2020 (Jan - Dec)
- [ ] 2020 (Jan - Feb)

Cumulus has Feb 2021 - now

**Comment by adamscarberry** [comment]
@jeffsuperglide @willbreitkreutz @FHanbali   Working on CPC inventory here.

**Comment by brettpalmberg** [comment]
Setting from "In Progress" --> "Todo" to prioritize other Issues

**Comment by adamscarberry** [comment]
closing issue as CPC acquisition and delivery has been disabled for a few months now.
