### ISSUE TITLE
[CHECKLIST]: Geo Processor Code Review

### ISSUE THREAD

**Issue by jeffsuperglide** [USACE/cumulus#198]
## General Description
Geo Processor container code review, refactor, and processor evaluation.  Initial review of processor code and fixes provided an opportunity to optimize, document, and define a standard Python coding format.  Pylint and Black Python packages are used to implement a code formatting standard with Numpy docstring formatting to document classes, method, and modules.  Optimization of the code has helped reduce redundant code, better documentation and better readability.  Documentation can be generated from the code instead of double documenting.

## TODO
- [x] Refactoring Code
- [x] Implement Pylint and Black with Numpy as the docstring format
- [x] Processor Review and bug fixes

**Comment by adamscarberry** [comment]
@jeffsuperglide 

Reviewing branch: https://github.com/USACE/cumulus-api/tree/refactor/complete-overhaul-snodas

- [ ] HRRR appears to be fixed.  Resulting DSS looks good.  
- [ ] Need DB Migration to set temporal_duration back to 3600 (back to PER-CUM in DSS)
- [ ] SNODAS Interpolated needs date fix - showing one day behind primary product
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/46494851/166070052-fcf77f0f-ffec-4a62-ad96-3fd6838b8a89.png">

**Comment by adamscarberry** [comment]
Spot checking products.  

Develop vs Stable - matches

- [ ] NDGD RTMA AIRTEMP 1hr
- [ ] NDGD RTMA PRECIP 1hr

**Comment by adamscarberry** [comment]
@jeffsuperglide Do we need to check anything else before closing this?
