### ISSUE TITLE
[CHECKLIST]: Data Reprocessing with Bugfixed Geoprocessors

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#233]
## Reprocessing Data Archives?

Related to geoprocessor fixes here: USACE/cumulus-api#321

## List Title
- [ ] Files from async_geoprocess/src/cumulus_geoproc/processors/nohrsc-snodas-assimilated.py
- [ ] Files from async_geoprocess/src/cumulus_geoproc/processors/wrf-columbia-airtemp.py
- [ ] Files from async_geoprocess/src/cumulus_geoproc/processors/wrf-columbia-precip.py

**Comment by adamscarberry** [comment]
## SNODAS Corrections SWE 24hr
Acquirable: nohrsc-snodas-assimilated
Product: SNODAS Corrections SWE 24hr

Cleared db records before 2022-07-18:
- [ ] Develop
- [ ] Stable

Delete COGs prior to 2022-07-18

- [ ] Develop
- [ ] Stable

Reprocessed last few available products from June 2022
- [ ] Develop
- [ ] Stable

**Comment by adamscarberry** [comment]
Per Tim's email from 5/17/22:


> You might remember that about a year ago, we processed WRF Columbia precipitation and temperature data in Cumulus.  We are thinking that it would be good to reprocess the WRF Columbia data so that the COGs are stored referenced to NAD83 and not referenced to a sphere (which is what the source data is in).  We also have two other separate WRF datasets that we would like to process: WRF Willamette and WRF British Columbia.  Is it ok with you if we do the processing in Cumulus like before?

I think @jeffsuperglide was coordinating with Tim.

**Comment by brettpalmberg** [comment]
@adamscarberry @jeffsuperglide @timbbaldwin 

Connected with @timbbaldwin, he is working on the details of how to do the spatial resample and will coordinate when ready. 👍🏻

**Comment by willbreitkreutz** [comment]
Tabled due to inactivity
