### ISSUE TITLE
[BUG]: Productfile Validation and Database/S3 Cleanup Related to Issue #296

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#299]
Related to fix in USACE/cumulus-geoproc#8, original bug USACE/cumulus#296

We need to validate DSS Download from Stable or Confirm that Input File Has 1 Band. This will help us determine whether S3 files or database records are erroneous and need to be removed.

@brettpalmberg to automate detection of any input files that only have one band. These products should be unaffected by bug USACE/cumulus#296 and should not require any S3 or database data cleanup.

- [x] abrfc-qpe-01h - see notes below
- [x] cbrfc-mpe
- [x] cnrfc-qpe-06h - see notes below
- [x] hrrr-total-precip - see notes below
- [x] lmrfc-qpe-01h
- [x] lmrfc-qpf-06h
- [x] marfc-fmat-06h - LDM - no recent data to cleanup
- [x] marfc-nbmt-01h
- [x] marfc-nbmt-03h - 🛑 LDM
- [x] marfc-rtmat-01h
- [x] mbrfc-krf-fct-airtemp-01h
- [x] mbrfc-krf-qpe-01h
- [x] mbrfc-krf-qpf-06h
- [x] naefs-mean-06h - LDM - DSS results look similiar before and after 11-Aug
- [x] nbm-co-01h - seperate cleanup being tracked https://github.com/USACE/cumulus/issues/298
- [x] ncep-mrms-gaugecorr-qpe-01h - we don't acquire data for this currently
- [x] ncep-mrms-v12-msqpe01h-p1-alaska
- [x] ncep-mrms-v12-msqpe01h-p1-carib
- [x] ncep-mrms-v12-msqpe01h-p2-alaska
- [x] ncep-mrms-v12-msqpe01h-p2-carib
- [x] ncep-mrms-v12-multisensor-qpe-01h-pass1
- [x] ncep-mrms-v12-multisensor-qpe-01h-pass2
- [x] ncep-rtma-ru-anl-airtemp - also tracked here: https://github.com/USACE/cumulus/issues/290
- [x] ncep-stage4-mosaic-01h
- [x] ncep-stage4-mosaic-06h
- [x] ncep-stage4-mosaic-24h
- [x] ncrfc-fmat-01h - 🛑 LDM
- [x] ncrfc-mpe-01h
- [x] ncrfc-rtmat-01h
- [x] ndfd-conus-airtemp - appears ok ✅ 
- [x] ndfd-conus-qpf-06h - still have this problem https://github.com/USACE/cumulus/issues/286
- [x] ndgd-leia98-precip - appears ok ✅ 
- [x] ndgd-ltia98-airtemp - appears ok ✅ 
- [x] nohrsc-snodas-assimilated - no recent data
- [x] nohrsc-snodas-unmasked - appears ok ✅ 
- [x] nsidc-ua-swe-sd-v1 - not a realtime product
- [x] prism-ppt-early - appears ok ✅ 
- [x] prism-ppt-stable - data not realtime
- [x] prism-tmax-early - appears ok ✅ 
- [x] prism-tmax-stable - data not realtime
- [x] prism-tmin-early - appears ok ✅ 
- [x] prism-tmin-stable- data not realtime
- [x] serfc-qpe-01h - no files to cleanup, product outage: https://github.com/USACE/cumulus/issues/300
- [x] serfc-qpf-06h - no files to cleanup, product outage: https://github.com/USACE/cumulus/issues/300
- [x] wpc-qpf-2p5km - appears ok ✅ 
- [x] wrf-columbia-airtemp - archive will be reprocessed soon
- [x] wrf-columbia-precip - archive will be reprocessed soon

For 🛑  LDM products, we could just delete files between 10-Aug-22 and now.

**Comment by brettpalmberg** [comment]
These products should be unaffected by bug https://github.com/USACE/cumulus/issues/296 and should not require any S3 or database data cleanup. Sample files only contain one band per file. Checking these off of the list above.

```
1 bands;  ./cbrfc-mpe;   ./cbrfc-mpe/xmrg0809202212z.grb
1 bands;  ./lmrfc-qpe-01h;   /vsigzip/./lmrfc-qpe-01h/2022080914z.grib.gz
1 bands;  ./lmrfc-qpf-06h;   /vsigzip/./lmrfc-qpf-06h/ORN_QPF_SFC_2022080912_234_2022081906f234.grb.gz
1 bands;  ./marfc-nbmt-01h;   ./marfc-nbmt-01h/RHA_T_NBM_9hr.2022-08-09.20z.grb
1 bands;  ./marfc-rtmat-01h;   ./marfc-rtmat-01h/RHA_T_RTMA_1hr.2022-08-09.19z.grb
1 bands;  ./mbrfc-krf-fct-airtemp-01h;   /vsigzip/./mbrfc-krf-fct-airtemp-01h/krf_hourly_ftemps_grib_2022082501f373.grb.gz
1 bands;  ./mbrfc-krf-qpe-01h;   /vsigzip/./mbrfc-krf-qpe-01h/krfqpe_2022080921z.grib.gz
1 bands;  ./mbrfc-krf-qpf-06h;   /vsigzip/./mbrfc-krf-qpf-06h/krf_qpf_grib_2022080918f168.grb.gz
1 bands;  ./ncep-mrms-v12-msqpe01h-p1-alaska;   /vsigzip/./ncep-mrms-v12-msqpe01h-p1-alaska/MRMS_MultiSensor_QPE_01H_Pass1_00.00_20220809-150000.grib2.gz
1 bands;  ./ncep-mrms-v12-msqpe01h-p1-carib;   /vsigzip/./ncep-mrms-v12-msqpe01h-p1-carib/MRMS_MultiSensor_QPE_01H_Pass1_00.00_20220809-150000.grib2.gz
1 bands;  ./ncep-mrms-v12-msqpe01h-p2-alaska;   /vsigzip/./ncep-mrms-v12-msqpe01h-p2-alaska/MRMS_MultiSensor_QPE_01H_Pass2_00.00_20220809-150000.grib2.gz
1 bands;  ./ncep-mrms-v12-msqpe01h-p2-carib;   /vsigzip/./ncep-mrms-v12-msqpe01h-p2-carib/MRMS_MultiSensor_QPE_01H_Pass2_00.00_20220809-150000.grib2.gz
1 bands;  ./ncep-mrms-v12-multisensor-qpe-01h-pass1;   /vsigzip/./ncep-mrms-v12-multisensor-qpe-01h-pass1/MRMS_MultiSensor_QPE_01H_Pass1_00.00_20220809-150000.grib2.gz
1 bands;  ./ncep-mrms-v12-multisensor-qpe-01h-pass2;   /vsigzip/./ncep-mrms-v12-multisensor-qpe-01h-pass2/MRMS_MultiSensor_QPE_01H_Pass2_00.00_20220809-150000.grib2.gz
1 bands;  ./ncep-stage4-mosaic-01h;   ./ncep-stage4-mosaic-01h/st4_conus.2022081004.01h.grb2
1 bands;  ./ncep-stage4-mosaic-06h;   ./ncep-stage4-mosaic-06h/st4_conus.2022080718.06h.grb2
1 bands;  ./ncep-stage4-mosaic-24h;   ./ncep-stage4-mosaic-24h/st4_conus.2022080512.24h.grb2
1 bands;  ./ncrfc-mpe-01h;   ./ncrfc-mpe-01h/MSR_mpe-lx_2022080922z.grb
1 bands;  ./ncrfc-rtmat-01h;   ./ncrfc-rtmat-01h/msr-coe-1hrT--NCRFC_RTMA_Obs_1hrT_2022080921z.grb
```

**Comment by adamscarberry** [comment]
## ABRFC-QPE

![image](https://user-images.githubusercontent.com/46494851/186488389-e58f06da-b837-450e-8ecc-574fff159e19.png)

Unsure which is correct.  Stable could be grabbing wrong band, but unsure at the moment.

**Comment by adamscarberry** [comment]
## CNRFC-QPE-06h

Difficult to test with no precip in area.

Stats look better with local:

![image](https://user-images.githubusercontent.com/46494851/186491369-e6054b7b-2db0-476c-aa3f-baa56c2982d8.png)

**Comment by adamscarberry** [comment]
## hrrr-total-precip

**Comment by adamscarberry** [comment]
## ncep-rtma-ru-anl-airtemp

see https://github.com/USACE/cumulus/issues/290

**Comment by adamscarberry** [comment]
## nbm-co-01h

see https://github.com/USACE/cumulus/issues/298

**Comment by adamscarberry** [comment]
## ndfd-conus-qpf-06h
