### ISSUE TITLE
[CHECKLIST]: patch cumulus-geoproc and cumulus-api async_geoprocess

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#359]
- [x] Patch and test cumulus-geoproc locally
- [x] Patch and test cumulus-api/async_geoprocess
- [x] merge and deploy cumulus-api/async_geoprocess to `develop`
- [x] merge and deploy cumulus-api/async_geoprocess to `stable`

**Comment by adamscarberry** [comment]
<img width="1604" alt="image" src="https://github.com/USACE/cumulus/assets/46494851/b60ba8c4-8c10-4f29-9e92-ee1d41eb6239">
