### ISSUE TITLE
[CHECKLIST]: patch cumulus-packager

### ISSUE THREAD

**Issue by jeffsuperglide** [USACE/cumulus#360]
## General Description
Ubuntu GPG error: signatures couldn't be verified

## Cumulus Packager Test and Confirm
- [x] Patch and test cumulus-packager locally
- [x]  merge and deploy cumulus-api/async_packager to develop
- [x]  merge and deploy cumulus-api/async_packager to stable
