### ISSUE TITLE
[CHECKLIST]: patch go api

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#361]
- [x] Upgrade to 1.19
- [x] Update packages to latest version
- [x] deploy to develop
- [x] deploy to stable
