### ISSUE TITLE
[CHECKLIST]: patch async_listener

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#362]
- [x] Upgrade to 1.19
- [x] Update packages to latest version
- [x] deploy to develop
- [x] deploy to stable
