### ISSUE TITLE
[FEATURE REQUEST]: NWW Little Wood River watershed bonding box update

### ISSUE THREAD

**Issue by jeffsuperglide** [USACE/cumulus#379]
## Feature Request Type
- [x] ***Watershed Extents (bounding box)***

## Is your feature request related to a problem? Please describe.
NWW Little Wood River Basin bounding box does not cover the entire extents of the watershed.

## Describe the solution you'd like
Update the existing NWW Little Wood River Basin bounding box to include, with a buffer, the watershed.

## Describe alternatives you've considered
NA

## Additional context
NWW Little Wood River Basin feature class attached
[Little Wood Map.zip](https://github.com/USACE/cumulus/files/12898298/Little.Wood.Map.zip)

## Tasks

- [x] Extract bounding box with buffer
- [x] View locally comparing bonding box to provided watershed(s)
- [x] Merge into `develop` and extract grids for provided watershed(s)
- [x] Merge into `stable`

**Comment by jeffsuperglide** [comment]
Little Wood River bounding box with additional buffer.

PR [#450](https://github.com/USACE/cumulus-api/pull/450)

<img width="748" alt="image" src="https://github.com/USACE/cumulus/assets/37386268/8416a074-1908-4657-9361-eecf56459d45">

**Comment by jeffsuperglide** [comment]
Changes merged into `develop`.  Download request made for NWW Little Wood River as GeoTiff tar.gz.  Image below is from QGIS showing original shapefiles provided and GeoTiffs.

<img width="601" alt="image" src="https://github.com/USACE/cumulus/assets/37386268/dd49971f-c117-440c-9e2f-c60ec2be40df">
