### ISSUE TITLE
[CHECKLIST]: patch go api

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#384]
## General Description
patch go api

- [x] Upgrade packages to latest, bump go runtime from 1.19 to 1.20
- [x] deploy to develop https://github.com/USACE/cumulus-api/pull/455
- [x] deploy to stable https://github.com/USACE/cumulus-api/pull/456
