### ISSUE TITLE
[CHECKLIST]: patch async_geoprocess

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#414]
## General Description

- Upgrade to the latest available gdal ubuntu full image which is ghcr.io/osgeo/gdal:ubuntu-full-3.9.1
- This upgrades python to 3.12 and may require some Dockerfile adjustments for packages

This will include `cumulus-geoproc` image and Dockerfile updates as well

## Tasks
- [x] Upgrade async_geoprocess base image to ghcr.io/osgeo/gdal:ubuntu-full-3.9.1
- [x] Upgrade cumulus-geoproc base image to ghcr.io/osgeo/gdal:ubuntu-full-3.9.1
- [x] Make needed Dockerfile adjustments
- [x] Test locally with random products from Airflow, compare geotif results with stable deployment (via downloads of geotifs)
- [x] Deploy to Develop
- [x] Deploy to Stable
