### ISSUE TITLE
[CHECKLIST]: patch async_packager

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#416]
## General Description

- Upgrade to the latest available gdal ubuntu full image which is ghcr.io/osgeo/gdal:ubuntu-full-3.9.1
- This upgrades python to 3.12 and may require some Dockerfile adjustments for packages

## Tasks
- [ ] Upgrade async_packager base image to ghcr.io/osgeo/gdal:ubuntu-full-3.9.1
- [ ] Make needed Dockerfile adjustments
- [ ] Test locally with random products from Airflow, verify downloads
- [ ] Deploy to Develop
- [ ] Deploy to Stable
