### ISSUE TITLE
[CHECKLIST]: Cumulus Map Explorer Features List

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#430]
## General Description
This is a master check list for the development of a Cumulus Map Explorer.

## Map Explorer Features List
- [ ] Add Map Layers, in particular North America map.
- [ ] Support shapefile uploads for user-defined Area-of-Interest download requests
- [ ] Support ad hoc drawing for user-defined Area-of-Interest download requests
- [ ] Integrate with catalog filtering, product selection, and time window specification for Area-of-Interest download requests

**Comment by FHanbali** [comment]
#339
