### ISSUE TITLE
Deploy Develop and Stable Versions of Application

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#90]
- [x] Standup Develop and Stable Databases
  - [x] Add postgis extensions, tables, view, functions, triggers, roles
  - [x] Add initial seed data (office, product, watershed, acquirable)
- [x] Develop API Deployed
- [x] Stable API Deployed

**Comment by brettpalmberg** [comment]
# Deployment Punchlist

## Cumulus API and Terraform Deployment

- [ ] Update Github Workflows for USACE/cumulus-api to support `develop` and `stable` containers. Merge PR USACE/cumulus-api#79
- [ ] Merge PR USACE/cumulus-api#78
- [ ] Merge PR USACE/cumulus-api#77
- [ ] Clean Database `cwbi-cumulus_develop`
- [ ] Initialize Database `cwbi-cumulus_develop` with any new seed data
  - [ ] HRRR Acquirable
  - [ ] HRRR Product
  - [ ] Config Table
  - [ ] Role Changes for Config Table
- [ ] Launch Container(s) `api` and verify functionality (Terraform)
- [ ] Launch Container(s) `listener` and verify functionality (Terraform)
- [ ] Launch Container(s) `geoprocess` and verify functionality (Terraform)

## Airflow Workflows Against New API

- [ ] Update Terraform deployment of Airflow to use bucket `cwbi-data-develop` (deprecate use of `corpsmap-data` bucket)
- [ ] Merge PR USACE/airflow-config#19
- [ ] Update connection information new Cumulus API URL from Airflow User Interface
- [ ] Turn on Airflow DAG for Testing

## Additional Cumulus API and Data Migration

- [ ] Launch Container(s) `packager` and verify functionality
- [ ] Copy existing productfiles from bucket `corpsmap-data` to bucket `cwbi-data-develop`.

**Comment by brettpalmberg** [comment]
# Cumulus Terraform Deployment (STABLE)

This creates a `stable` replica of the application deployed in the punchlist above. This will allow us to validate changes in the `develop` instance of the application before making changes in `stable` (which is used by more people)

- [ ] Deploy API, Listener, Geoprocess, Packager Containers
- [ ] Add `cumulus-api.rsgis.dev` to application load balancer
- [ ] CNAME DNS Entry for `cumulus-api.rsgis.dev`
- [ ] Deploy user interface that points to `stable` api
- [ ] Copy productfiles from S3 bucket `cwbi-data-develop` to `cwbi-data-stable`
- [ ] Copy database records for `productfiles` from database `develop` to `stable`
- [ ] Turn on Airflow DAGs that work against `stable` API and S3 bucket `cwbi-data-stable`

**Comment by brettpalmberg** [comment]
cc @FHanbali
